export const products = [
  {
    id: 1,
    title: "Guitarra eléctrica Fender Stratocaster",
    price: 999.99,
    stock: 15,
    description: "Guitarra eléctrica de alta calidad con un tono clásico.",
    category: "instrumentos-de-cuerda",
    img: "https://res.cloudinary.com/dzayakwnj/image/upload/v1714301483/fender-player-stratocaster-mn-bcr_k9xjdy.jpg",
  },
  {
    id: 2,
    title: "Teclado Yamaha PSR-E373",
    price: 349.99,
    stock: 30,
    description: "Teclado portátil con múltiples funciones y estilos.",
    category: "instrumentos-de-teclado",
    img: "https://res.cloudinary.com/dzayakwnj/image/upload/v1714301540/PSR-E373-a-0002_93bf52d876e072939ce78e9d091770b9_myjkcr.jpg",
  },
  {
    id: 3,
    title: "Batería Pearl Export Series",
    price: 799.99,
    stock: 10,
    description: "Batería completa con excelente calidad de sonido.",
    category: "instrumentos-de-percusion",
    img: "https://res.cloudinary.com/dzayakwnj/image/upload/v1714301591/bateria-pearl-export-series-5-cuerpos-jet-black_tdti9a.jpg",
  },
  {
    id: 4,
    title: "Violín Stradivarius",
    price: 1999.99,
    stock: 5,
    description: "Violín de alta calidad para músicos exigentes.",
    category: "instrumentos-de-cuerda",
    img: "https://res.cloudinary.com/dzayakwnj/image/upload/v1714301639/Stradivarius-1_hv9s1t.jpg",
  },
  {
    id: 5,
    title: "Amplificador Marshall DSL40CR",
    price: 699.99,
    stock: 12,
    description: "Amplificador potente con excelente calidad de sonido.",
    category: "amplificadores",
    img: "https://res.cloudinary.com/dzayakwnj/image/upload/v1714301675/D_NQ_NP_619033-MLU54983042040_042023-O_okmjbz.webp",
  },
  {
    id: 6,
    title: "Saxofón alto Yamaha YAS-280",
    price: 1199.99,
    stock: 8,
    description: "Saxofón alto con un sonido suave y melodioso.",
    category: "instrumentos-de-viento",
    img: "https://res.cloudinary.com/dzayakwnj/image/upload/v1714301708/YAS-280-01_vwe7le.jpg",
  },
  {
    id: 7,
    title: "Guitarra acústica Taylor 114ce",
    price: 899.99,
    stock: 20,
    description: "Guitarra acústica con tono cálido y suave.",
    category: "instrumentos-de-cuerda",
    img: "https://res.cloudinary.com/dzayakwnj/image/upload/v1714301742/1GUETY114EE_teq1bi.jpg",
  },
  {
    id: 8,
    title: "Micrófono Shure SM58",
    price: 99.99,
    stock: 40,
    description: "Micrófono vocal con alta calidad y durabilidad.",
    category: "accesorios-de-audio",
    img: "https://res.cloudinary.com/dzayakwnj/image/upload/v1714301784/a469fdcd-microfono-profesional-shure-sm58-mejor-precio-original-6152-mla4627819659_072013-f_pppw0r.jpg",
  },
  {
    id: 9,
    title: "Piano digital Roland FP-30X",
    price: 799.99,
    stock: 14,
    description: "Piano digital portátil con un sonido impresionante.",
    category: "instrumentos-de-teclado",
    img: "https://res.cloudinary.com/dzayakwnj/image/upload/v1714301847/fp-30x-wh_side_angle_gal_pnu48v.jpg",
  },
  {
    id: 10,
    title: "Bajo eléctrico Ibanez SR300E",
    price: 549.99,
    stock: 18,
    description: "Bajo eléctrico con excelente tono y jugabilidad.",
    category: "instrumentos-de-cuerda",
    img: "https://res.cloudinary.com/dzayakwnj/image/upload/v1714301882/D_858790-MLA46092762388_052021-F-1_pfm9ut.jpg",
  },
];
